name: "Meal Planner"
description: "A simple meal planner with AI-powered ingredient formatting"
version: "v1.0.4"
slug: "meal_planner"
init: false
arch:
  - aarch64
  - amd64
ingress: true
panel_icon: "mdi:silverware-variant"
panel_title: "Meal Planner"
ports:
  "3001/tcp": 3001
webui: "http://[HOST]:[PORT:3001]"
options:
  gemini_api_key: ""
schema:
  gemini_api_key: "str?"
map:
  - config:rw
  - share:rw
image: "ghcr.io/lordee/{arch}-meal-planner"