name: HACS Validation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: HACS validation
        uses: hacs/action@main
        with:
          category: integration
          github_token: ${{ secrets.GITHUB_TOKEN }}
